<a href="https://colab.research.google.com/github/IT21177828/pytorch_practice/blob/main/intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [1]:
import torch
import numpy as np

In [5]:
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [10]:
np1 = np.random.rand(3,4)
np1

array([[0.29372294, 0.42559892, 0.09035197, 0.08214709],
       [0.22209159, 0.64536257, 0.53300783, 0.81537259],
       [0.51992219, 0.24615954, 0.99528744, 0.68274851]])

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.9233, -1.5708,  1.0479, -2.2246],
        [-1.7004,  0.2909,  0.5278,  0.2582],
        [-0.3347, -1.5703,  0.6677,  0.7404]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])